### PR TITLE
Add LO coloured block, reorg welcome back into a preface section

### PR DESCRIPTION
**Pull request by tanho63**
Also: 

- deleted Data folder (not used in this book club, probably)
- added text to the welcome RMD (please review)

### CODE REVIEW

**Comment by tanho63** [comment]
Sample build here: https://tanho63.github.io/bookclub-rpkgs/Companion/docs/welcome.html

**Comment by jonthegeek** [comment]
Welcome hops around in the index, and I think the Machete order actually makes sense in Chapter 1 (since a LO of chapter 1 is to get familiar with the table of contents). I'm not sure the welcome is necessary.

**Comment by tanho63** [comment]
Hmm. That's annoying re: jumping around the index, need to brush up my bookdown-fu. I think the goals and mechanics (ie block colours etc) of the companion should be standalone from the week 1 itself, and am amenable to whether the order belongs in either page

**Review by jonthegeek — CHANGES_REQUESTED** [review]
Making this a formal review so it (I think) threads. Welcome jumps around in the index. I like having the formatting stuff in it, but not if we can't get it to stay in the right place in the index.

I think the Machete Order stuff should go in Chapter 1 since one of the LOs is to be familiar with the table of contents.

(I agree with your last comment, in other words)

**Comment by tanho63** [comment]
https://tanho63.github.io/bookclub-rpkgs/Companion/docs/welcome.html 

This seems to have rendered the changes I wanted it to. I patched the jump around issue for now by listing explicitly. 

Issues to be solved in new PR: 

- fleshing out other pages so we can set up LOs for week 2+ (sooner rather than later)
- deciding order of future weeks (as laid out in Readme or in Companion, they should match)

**Comment by jonthegeek** [comment]
Apply LO formatting for chapter 2, then this will be ready.

**Comment by tanho63** [comment]
@jonthegeek done

**Review by jonthegeek — APPROVED** [review]
Woot!

**Pull request merged**
