### PR TITLE
Create "build" folder so that the rest of the docs can live happily at the Companion folder level

### PR DESCRIPTION
**Pull request by tanho63**
Moved the component files into a build folder and changed bookdown.yml to point at the parent directory.

New script for building book: 
```
setwd(here::here('Companion/build'))
bookdown::render_book('companion')
setwd(here::here())
```

### CODE REVIEW

**Review by jonthegeek — APPROVED** [review]
LGTM!

**Comment by jonthegeek** [comment]
> New script for building book:
> 
> ```
> setwd(here::here('Companion/build'))
> bookdown::render_book('companion')
> setwd(here::here())
> ```

Can you add this to the Companion folder as something like build.R? I don't think it'd break anything.

**Review by jonthegeek — CHANGES_REQUESTED** [review]
See latest comment.

**Comment by tanho63** [comment]
> > New script for building book:
> > ```
> > setwd(here::here('Companion/build'))
> > bookdown::render_book('companion')
> > setwd(here::here())
> > ```
> 
> Can you add this to the Companion folder as something like build.R? I don't think it'd break anything.

Done.

**Review by jonthegeek — APPROVED** [review]
Woot!

**Pull request merged**
